PP4_Cityfur/urls.py
from django.contrib import admin
from django.urls import path, include

# Import views from apps
# from guests import views as guests_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("", include("guests.urls"), name="guests-urls"),
    path("", include("reports.urls"), name="reports-urls"),
    path("accounts/", include("allauth.urls")),
]

guests/urls.py
from django.urls import path
from .views.guests_list_views import guests_list_view, guests_list_all_view
from .views.guest_details_views import guest_details_view
from .views.add_guests_views import add_guest_view, update_guest_view

urlpatterns = [
    path('', guests_list_view, name='home'),
    path('guests/', guests_list_view, name='guests_list_temp'),
    path('guests/all/', guests_list_all_view, name='guests_list_all_temp'),
    path('guests/add_guest/', add_guest_view, name='add_guest_temp'),
    path(
        'guests/update_guest/<int:id>',
        update_guest_view, name='update_guest_temp'),
    path('guests/<slug:slug>/', guest_details_view, name='guest_details_temp'),
]

guests/models.py
from django.db import models
from django.utils.text import slugify

# Lists of choices
GENDER = ((0, "Male"), (1, "Female"), (2, "Other"))


# Create model for customer
class Customer(models.Model):
    """Creates a model for customers.

    Args:
        models: The base model class.

    Attributes:
        id (int): The unique identifier for the customer.
        first_name (str): The first name of the customer.
        last_name (str): The last name of the customer.
        address (str): The address of the customer.
        phone (str): The phone number of the customer.
        email (str): The email address of the customer.
        information (str): Additional information about the customer.
        created_on (datetime): The date and time when the customer was created.
        updated_on (datetime): The date and time when the customer was updated.
        ___str___: Returns the full name of the customer.
    """

    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=15)
    email = models.EmailField(null=True, blank=True)
    information = models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    # Orders customers by last name
    class Meta:
        ordering = ["last_name"]

    # Returns the full name of the customer
    def __str__(self):
        return f"{self.last_name} {self.first_name}"


# Create model for guest
class Guest(models.Model):
    """
    Creates a model for guests.

    Args:
        models: The base model class.

    Attributes:
        id (AutoField): The primary key for the guest.
        first_name (CharField): The first name of the guest.
        last_name (CharField): The last name of the guest.
        name_addon (CharField): An additional name for the guest.
        gender (IntegerField): The gender of the guest.
        image (ImageField): An image of the guest.
        date_of_birth (DateField): The date of birth of the guest.
        information (TextField): Additional information about the guest.
        food (BooleanField): Indicates if the guest requires food.
        food_time_1 (TimeField): The first food time for the guest.
        food_time_2 (TimeField): The second food time.
        food_time_3 (TimeField): The third food time.
        medication (BooleanField): Indicates if the guest requires medication.
        medication_time_1 (TimeField): The first medication time for the guest.
        medication_time_2 (TimeField): The second medication time.
        medication_time_3 (TimeField): The third medication time.
        created_on (DateTimeField): The date and time the guest was created.
        updated_on (DateTimeField): The date and time the guest was updated.
        customer_id (ForeignKey): The foreign key to the associated customer.
        slug (SlugField): A unique slug for the guest.

    Methods:
        save: Overrides the save method to automatically
            generate a slug for the guest.
        get_gender: Translates the gender coding to categories.
        get_last_name: Returns the last name of the guest.
        __str__: Returns a string representation of the guest.
    """
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    name_addon = models.CharField(max_length=50, null=True, blank=True)
    gender = models.IntegerField(choices=GENDER, default=0)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    date_of_birth = models.DateField(null=True, blank=True)
    information = models.TextField(null=True, blank=True)
    food = models.BooleanField(default=False)
    food_time_1 = models.TimeField(null=True, blank=True)
    food_time_2 = models.TimeField(null=True, blank=True)
    food_time_3 = models.TimeField(null=True, blank=True)
    medication = models.BooleanField(default=False)
    medication_time_1 = models.TimeField(null=True, blank=True)
    medication_time_2 = models.TimeField(null=True, blank=True)
    medication_time_3 = models.TimeField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, blank=True)

    # Orders guests by first name
    class Meta:
        ordering = ["first_name"]

    # Automatically creates a slug for the guest
    # by combining first_name and name_addon
    def save(self, *args, **kwargs):
        if not self.slug:
            if self.name_addon is None:
                self.slug = slugify(self.first_name)
            else:
                self.slug = slugify(f"{self.first_name}-{self.name_addon}")
        super().save(*args, **kwargs)

    # Translates gender coding to categories
    def get_gender(self):
        if self.gender == 0:
            return "Male"
        elif self.gender == 1:
            return "Female"
        elif self.gender == 2:
            return "Other"
        else:
            return "Not defined"

    # Returns the full name of the guest
    def get_last_name(self):
        if self.last_name is None:
            return ""
        else:
            return self.last_name

    # Returns all necessary information about the guest
    def __str__(self):
        return (
            f"{self.first_name} {self.get_last_name()} "
            f"({self.name_addon}) {self.get_gender()}"
        )


# Create model for tracking guest presence
class Presence(models.Model):
    """
    Returns a string representation of the Presence model.

    Returns:
        str: A string containing the date, check-in time,
            check-out time, guest's first name,
            last name, ID, and pickup name.
    """

    id = models.AutoField(primary_key=True)
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)
    date = models.DateField()
    check_in = models.TimeField(blank=True, null=True)
    check_out = models.TimeField(blank=True, null=True)
    pickup_name = models.CharField(max_length=50, null=True, blank=True)

    # Only one entry of the combination of guest and date allowed
    class Meta:
        unique_together = ("guest", "date")

    # Return all necessary information about the presence of a guest
    def __str__(self):
        return (
            f"{self.date} {self.check_in} "
            f"{self.check_out} {self.guest.first_name} "
            f"{self.guest.last_name} {self.guest.id} "
            f"{self.pickup_name}"
        )

guests/views/add_guests_views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from ..models import Guest
from ..forms import AddGuest


# Function for adding guest to database including an image upload.
def add_guest_view(request):
    """
    This view function handles the addition of a new guest.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """

    if request.method == "POST":
        form = AddGuest(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            guest = form.save()
            guest_name = (
                f"{guest.first_name} "
                f"{guest.name_addon if guest.name_addon else ''}"
            )
            messages.add_message(
                request,
                messages.SUCCESS,
                f"Profile for {guest_name} has been added successfully.",
            )
            return HttpResponseRedirect(f"/guests/{guest.slug}")

    else:
        form = AddGuest()

    return render(request, "guests/add_guest_temp.html", {"form": form})


# Function for updating guest information
def update_guest_view(request, id):
    """
    This function helps to update the information of a guest.

    Args:
        request (HttpRequest): The HTTP request object.
        id (int): The ID of the guest to be updated.

    Returns:
        HttpResponse: The HTTP response object.
    """

    guest = get_object_or_404(Guest, id=id)
    guest_name = (
        f"{guest.first_name} "
        f"{guest.name_addon if guest.name_addon else ''}"
    )
    if request.method == "POST":
        form = AddGuest(request.POST, request.FILES, instance=guest)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f"Profile of {guest_name} has been updated successfully.",
            )
            return HttpResponseRedirect(f"/guests/{guest.slug}")

    else:
        form = AddGuest(instance=guest)

    return render(
        request, "guests/update_guest_temp.html",
        {"form": form, "guest": guest}
    )

guests/views/guest_details_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from ..models import Guest
from reports.models import Report


# View function for guest details
def guest_details_view(request, slug):
    """
    View function to display the details of a guest.

    Args:
        request (HttpRequest): The HTTP request object.
        slug (str): The slug of the guest.

    Returns:
        HttpResponse: The HTTP response object containing
            the rendered template.
    """

    queryset = Guest.objects.all()
    guest = get_object_or_404(queryset, slug=slug)

    def guest_custumor():
        if guest.customer_id:
            return guest.customer_id
        else:
            return None

    customer = guest_custumor()

    if request.method == "POST" and "delete" in request.POST:
        guest_name = (
            f"{guest.first_name} "
            f"{guest.name_addon if guest.name_addon else ''}"
        )
        guest.delete()
        messages.add_message(
            request,
            messages.SUCCESS,
            f"Profile of {guest_name} has been deleted successfully.",
        )
        return redirect("/")

    guest_reports = (
        Report.objects.filter(guests=guest).order_by('-report_date')
    )
    context = {"guest": guest,
               "customer": customer,
               "guest_reports": guest_reports,
               }

    return render(request, "./guests/guest_details_temp.html", context)

guests/templates/guests/add_guest.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="form-group">
    <form action="" method=POST enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" class="btn btn-secondary">
    </form>
</div>

{% endblock content %}

guests/templates/guests/add_guest_temp.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block content %}

<div class="menu-bubble d-lg-none" id="sidebar-toggle">
    <span class="fa-solid fa-bars fa-2x icon-fa" ></span>
</div>

<div class="row pt-4 mx-auto">

    {% if user.is_authenticated %}

        {{ form.media }}

        <div class="form-group">
            <h1>Add guest</h1>
            <br>
            <form method=POST enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}               

                <div class="pt-3">
                    <input type="submit" value="Add" class="btn btn-primary btn-lg active">
                    <a class="btn btn-danger btn-lg active" role="button"  href="/">
                        Cancel
                    </a>
                </div>
            </form>
        </div>

        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

    {% endif %}

</div>

{% endblock content %}

guests/templates/guests/guest_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Header -->
<header>
    {% block header_nav %}
    {% include "guests/components/header_details.html" %}
    {% endblock header_nav %}
</header>


<div class="row p-4  mx-auto container-fluid">

    <div class="col-4">
        {% if guest.image %}
            <img src="{{ guest.image.url }}" alt="{{ guest.first_name }}-{{ guest.name_addon }}" class="img-fluid">
        {% else %}
            <img src={% static "/images/anonymdog.jpg" %} alt="No image was found" class="img-fluid">
        {% endif %}
    </div>


    <div class="col-8">
        <div class="col px-0">
            <div class="row">
                <!-- Show name and name_addon -->
                <div class="col-auto">
                    <h4 class="mb-0">{{ guest.first_name }}</h4>
                    <!-- Show name addon if it exists -->
                    {% if guest.name_addon %}
                    <span>{{ guest.name_addon }}</span>
                    {% else %}
                    <span><br></span>
                    {% endif %}                                     
                </div>
                <!-- Show gender depending on the database entry -->
                <div class="col px-0">
                    {% if guest.get_gender_display == "Male" %}
                    <span class="fa-solid fa-mars fa-lg icon-fa"></span>
                    {% elif guest.get_gender_display == "Female" %}
                    <span class="fa-solid fa-venus fa-lg icon-fa"></span>
                    {% else %} 
                    <spanclass="fa-solid fa-genderless fa-lg icon-fa"></span>
                    {% endif %}
                </div>
            </div>
            <div>
                {{ guest.customer_id.address }}<br />
                {{ guest.customer_id.first_name }}<br />
                {{ guest.customer_id.last_name }}<br />
                {{ guest.customer_id.phone }}<br />
                {{ guest.customer_id.information }}<br />
                <span>Go to customer profil</span>
            </div>
    </div>

</div>

{% endblock content %}

guests/templates/guests/guest_details_temp.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    {% if user.is_authenticated %}

        <!-- Displaying django messages -->
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    {% for message in messages %}
                        <div class="alert alert-dismissible fade show alert-box" id="msg" role="alert">
                            <div class="my-1">{{ message | safe }}</div>
                            <button type="button" class="btn-close alert-box-btn" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <!-- Menu bubble -->
        <div class="menu-bubble d-lg-none" id="sidebar-toggle">
            <span class="fa-solid fa-bars fa-2x icon-fa" ></span>
        </div>
    
        <div class="p-4 mx-auto container-fluid">
            <div class="row profile rounded p-3">
                <div class="col-4">
                    <div>
                    {% if guest.image %}
                        <img src="{{ guest.image.url }}" alt="{{ guest.first_name }}-{{ guest.name_addon }}" class="img-fluid">
                    {% else %}
                        <img src={% static "/images/anonymdog.webp" %} alt="No image was found" class="img-fluid">
                    {% endif %}
                    </div>
                    <div class="pt-3">
                        <a class="btn btn-primary btn-md active" role="button" href="/guests/update_guest/{{ guest.id }}">
                            Edit guest profile
                        </a>
                    </div>
                    <div class="pt-3">
                        <a class="btn btn-danger btn-ms active modal-trigger" role="button" data-toggle="modal" data-target="#delete-modal-{{ guest.id }}">
                            Delete profile
                        </a>
                    </div>
                </div>

                <div class="col-8">
                    <div class="col px-0">
                        <div class="row mb-3">
                            <!-- Show name and name_addon -->
                            <div class="col-auto">
                                <h1 class="mb-0">{{ guest.first_name }}</h1>
                                <!-- Show name addon if it exists -->
                                {% if guest.name_addon %}
                                <span>({{ guest.name_addon }})</span>
                                {% else %}
                                <span><br></span>
                                {% endif %}                                     
                            </div>
                            <!-- Show gender depending on the database entry -->
                            <div class="col px-0">
                                {% if guest.get_gender_display == "Male" %}
                                <span class="fa-solid fa-mars fa-lg icon-fa"></span>
                                {% elif guest.get_gender_display == "Female" %}
                                <span class="fa-solid fa-venus fa-lg icon-fa"></span>
                                {% else %} 
                                <spanclass="fa-solid fa-genderless fa-lg icon-fa"></span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="mb-3">
                            <h2>Owner Information</h2>
                            <span>First name {{ guest.customer_id.first_name }}</span><br>
                            <span>Last name: {{ guest.customer_id.last_name }}</span><br>
                            <span>Address: {{ guest.customer_id.address }}</span><br>
                            <span>Phone: {{ guest.customer_id.phone }}</span><br>
                            <span>Information: {{ guest.customer_id.information }}</span><br>
                        </div>
                        <div class="mb-3">
                            {% if guest.food %}
                                <h2>Food Times</h2>
                                <p>Food has to be served at these times:</p>
                                {{ guest.food_time_1 }}<br>
                                    {% if guest.food_time_2 != None %}
                                        {{ guest.food_time_2 }}<br>
                                    {% endif %}
                                    {% if guest.food_time_3 != None %}
                                        {{ guest.food_time_3 }}<br>
                                    {% endif %}
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            {% if guest.medication %}
                                <h2>Medication Times</h2>
                                <p>Medication has to be applied at these times:</p>
                                {{ guest.medication_time_1 }}<br>
                                {% if guest.medication_time_2 != None %}
                                    {{ guest.medication_time_2 }}<br>
                                {% endif %}
                                {% if guest.medication_time_3 != None %}
                                    {{ guest.medication_time_3 }}<br>
                                {% endif %}
                        {% endif %}
                        </div>
                        
                    </div>
                </div>
            </div>

            <!-- Modal for confirmation to delete profile -->
            <div class="modal fade" id="delete-modal-{{ guest.id }}" tabindex="-1" role="dialog" aria-labelledby="DeleteModalTitle{{ guest.id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="DeleteModalTitle{{ guest.id }}">
                                Delete profile of {{ guest.first_name }} 
                                {% if guest.name_addon %}
                                    <span>{{ guest.name_addon }}</span>
                                {% else %}
                                    <span><br></span>
                                {% endif %}
                            </h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{% url 'guest_details_temp' guest.slug %}" id="delete-form-{{ guest.id }}">
                                {% csrf_token %}
                                <input type="hidden" name="delete" value="true">
                                <div class="profile-check-out text-center rounded-bottom p-1 pointer" onclick="document.getElementById('delete-form-{{ guest.id }}').submit();">
                                    Delete profile
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row pt-4 mx-auto container-fluid">
            <h2>Reports mentioned:</h2>
            <div>
                {% if guest_reports %}
                    {% for report in guest_reports %}
                        <div class="my-2 list-item">
                            <div class="row profile rounded">
                                <div class="row p-2">
                                    <div class="col-9 mb-2">
                                        <b>{{report.report_date}}</b>
                                        <br>
                                        {{report.report_text}}
                                    </div>
                                    {% if report.guests.all|length > 0 %}
                                    <div>
                                        <div class="mb-2">
                                            <b>Guests:</b>
                                        </div>
                                        {% for guest in report.guests.all %}
                                            <a href="{% url 'guest_details_temp' guest.slug %}" class="text-decoration-none">    
                                                <span class="report-guest p-1">{{ guest.first_name }}{% if guest.last_name %} {{ guest.last_name }}{% endif %}{% if guest.name_addon %} ({{ guest.name_addon }}){% endif %}</span>
                                            </a>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                    <div class="m-2 text-end">
                                        <a  href="{% url 'report_details_temp' report.id %}" class="report-link">
                                            <span>Report details</span>
                                        </a>
                                    </div>    
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                {% else %}
                    <span>No Reports for this guest available</span>
                {% endif %}

            </div>
        </div>

    {% endif %}

{% endblock content %}

guests/templates/guests/update_guest_temp.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block content %}

    <div class="menu-bubble d-lg-none" id="sidebar-toggle">
        <span class="fa-solid fa-bars fa-2x" ></span>
    </div>

    <div class="row p-4 mx-auto container-fluid">

        {% if user.is_authenticated %}

            {{ form.media }}

            <div class="form-group">
                <h1>Update guest</h1>
                <br>
                <form method=POST enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <div class="pt-3">
                        <input type="submit" value="Update" class="btn btn-primary btn-lg active">
                        <a class="btn btn-danger btn-lg active" role="button"  href="/guests/{{ guest.slug }}/">
                            Cancel
                        </a>
                    </div>
                </form>
            </div>

            {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ field.label }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

        {% endif %}

    </div>

{% endblock content %}